// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Prefix      pgtype.Text
	KeyHash     string
	Scopes      []string
	Environment string
	Revoked     pgtype.Bool
	CreatedAt   pgtype.Timestamp
	ExpiresAt   pgtype.Timestamp
}

type Project struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID        uuid.UUID
	Email     string
	FirstName string
	LastName  pgtype.Text
	ClerkID   pgtype.Text
}
