// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    clerk_id,
    email,
    first_name,
    last_name
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, email, first_name, last_name, clerk_id
`

type CreateUserParams struct {
	ClerkID   pgtype.Text
	Email     string
	FirstName string
	LastName  pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ClerkID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ClerkID,
	)
	return i, err
}
