// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	Prefix      string
	KeyHash     string
	Scopes      []string
	Environment string
	Revoked     pgtype.Bool
	CreatedAt   pgtype.Timestamp
	ExpiresAt   pgtype.Timestamp
}
